apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-node-api
  labels:
    app: kubernetes-node-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-node-api
  template:
    metadata:
      labels:
        app: kubernetes-node-api
    spec:
      containers:
        - name: kubernetes-node-api
          image: driedsoba/kubernetes-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthyz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20

        